package merveyavuz_odev2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * 
 * @description File chooser ile seçilen dosyanın içindeki txt uzantılı olanları
 * okuyup text adlarını linked liste, içerisindeki kelimeleri ise ilgili nodea
 * alfabetik sıralı, binary search tree olarak atayan programdır. Arama Yap
 * kısmında, girilen kelime linked list ve bst ile oluşturulan yapıda arananarak
 * ekrana yazdırılır. Listele kısmında, oluşturulan yapı üzerinde alfabetik
 * olarak txt dosyaları ve içindekileri ekrana yazdırılır. Çıkış kısmında,
 * programdan çıkış yapılır.
 */
public class FrameProgram extends javax.swing.JFrame {

    /**
     * Creates new form FrameProgram
     */
    public LinkedList<String> linkedList = new LinkedList<>();
    String secilenDosya;

    public FrameProgram() {
        initComponents();
        CenteredFrame(this); 
        txt_okunanDosyaYolu.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_dosyaYoluOku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_okunanDosyaYolu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_islemCalistir = new javax.swing.JButton();
        jRadioButton_aramaYap = new javax.swing.JRadioButton();
        jRadioButtonListele = new javax.swing.JRadioButton();
        jRadioButton_Cikis = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_aranacakKelime = new javax.swing.JTextField();
        jlist_bulunanlar = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_dosyaYoluOku.setText("Dosya Yolu Oku");
        btn_dosyaYoluOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosyaYoluOkuActionPerformed(evt);
            }
        });

        jLabel1.setText("Okunan Dosya Yolu:");

        jLabel2.setText("İşlem Seçenekleri");

        btn_islemCalistir.setText("İşlem Çalıştır");
        btn_islemCalistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_islemCalistirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_aramaYap);
        jRadioButton_aramaYap.setText("Arama Yap");

        buttonGroup1.add(jRadioButtonListele);
        jRadioButtonListele.setText("Listele");

        buttonGroup1.add(jRadioButton_Cikis);
        jRadioButton_Cikis.setText("Çıkış");

        jLabel3.setText("Aranacak Kelime:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_dosyaYoluOku)
                    .addComponent(txt_okunanDosyaYolu, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButton_aramaYap)
                            .addComponent(jRadioButton_Cikis)
                            .addComponent(jRadioButtonListele))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(txt_aranacakKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_islemCalistir)
                            .addComponent(jlist_bulunanlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btn_dosyaYoluOku)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_okunanDosyaYolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_islemCalistir))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_aramaYap)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_aranacakKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonListele)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_Cikis))
                    .addComponent(jlist_bulunanlar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dosyaYoluOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dosyaYoluOkuActionPerformed

        //Dosya seçme işlemi
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Dosya Seçici");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("Secilen dosya : " + chooser.getSelectedFile());
        } else {
            System.out.println("Dosya bulunmadı");
        }
        secilenDosya = chooser.getSelectedFile().toString();
        txt_okunanDosyaYolu.setText(chooser.getSelectedFile().toPath().toString());

        Path dir = chooser.getSelectedFile().toPath(); //Dosya yolu bulunur
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir, "*.txt")) {
            for (Path entry : stream) { //dosya yolundaki textleri sırayla okur
                Node newNode = new Node(entry.getFileName().toString()); //Textler linked liste eklenir
                linkedList.addLast(newNode);
                Path p = Paths.get(chooser.getSelectedFile().toString(), entry.getFileName().toString()); //Dosya ve txtnin yollarını birleştirerek path oluşturur.

                Scanner input = new Scanner(new InputStreamReader(new FileInputStream(p.toString()), "ISO-8859-9")); //Türkçe karaktere uygun olarak text okur.
                LinkedList<String> kelimeler = new LinkedList<>();
                BST<String> bstKelimeler = new BST();
                while (input.hasNext()) {
                    String kelime = input.next();
                    Node wordNode = new Node(kelime);
                    kelimeler.addLast(wordNode); //Okunan kelimeleri linked liste atar
                }

                Node wordsTemp = kelimeler.head;
                while (wordsTemp != null) {
                    bstKelimeler.insert(wordsTemp.data.toString()); //kelimeler linkedlistindeki kelimeleri bstye ekler.
                    wordsTemp = wordsTemp.nextNode;
                }
                newNode.tree = bstKelimeler; //Oluşturulan bstyi okunan textin nodeuna ekler.

            }
        } catch (IOException x) {
            System.err.println(x);
        }


    }//GEN-LAST:event_btn_dosyaYoluOkuActionPerformed

    private void btn_islemCalistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_islemCalistirActionPerformed

        if (secilenDosya == null) {
            String message = "Lütfen dosya seçiniz";
            JOptionPane.showMessageDialog(new JFrame(), message, "UYARI",JOptionPane.WARNING_MESSAGE);
        } else {
            String aranan = txt_aranacakKelime.getText();
            if (jRadioButton_aramaYap.isSelected()) {
                jlist_bulunanlar.removeAll();
                linkedList.search(aranan);
                jlist_bulunanlar.add(linkedList.search(aranan));
            } else if (jRadioButtonListele.isSelected()) {
                jlist_bulunanlar.removeAll();
                Node temp = linkedList.head;
                while (temp != null) {
                    jlist_bulunanlar.add(temp.data.toString());
                    BST bstTemp = temp.tree;
                    jlist_bulunanlar.add(bstTemp.printTree());
                    temp = temp.nextNode;
                    bstTemp.sonuc.setLength(0);
                }

            } else if (jRadioButton_Cikis.isSelected()) {
                System.exit(0);
            }
        }


    }//GEN-LAST:event_btn_islemCalistirActionPerformed

     public void CenteredFrame(javax.swing.JFrame objFrame){ //Frame in ekranda merkezde olması için 
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dosyaYoluOku;
    private javax.swing.JButton btn_islemCalistir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonListele;
    private javax.swing.JRadioButton jRadioButton_Cikis;
    private javax.swing.JRadioButton jRadioButton_aramaYap;
    private java.awt.List jlist_bulunanlar;
    private javax.swing.JTextField txt_aranacakKelime;
    private javax.swing.JTextField txt_okunanDosyaYolu;
    // End of variables declaration//GEN-END:variables
}
